# Generated by Django 5.1.6 on 2025-03-14 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruser',
            name='newsletter_subscribed',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='zipcode',
        ),
    ]
