# Generated by Django 5.1.6 on 2025-03-14 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_loginuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='loginUser',
        ),
    ]
