# Generated by Django 5.1.6 on 2025-03-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_delete_loginuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image/'),
        ),
    ]
