# Generated by Django 5.1.6 on 2025-03-16 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_customeruser_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='total_spent',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
