# Generated by Django 5.1.6 on 2025-03-14 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0002_alter_order_user_alter_products_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagories',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image/'),
        ),
    ]
