# Generated by Django 5.1.6 on 2025-03-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0003_catagories_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='isFreeDelevary',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='offer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
