# Generated by Django 5.1.6 on 2025-03-18 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0005_alter_products_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='orders',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
    ]
