# Generated by Django 5.1.6 on 2025-03-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0006_remove_orderitem_name_remove_orderitem_orders_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
