# Generated by Django 5.1.6 on 2025-03-20 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productApp', '0008_orderitem_user_wishlistmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistmodel',
            name='iswishlist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
